// Code generated by protoc-gen-go. DO NOT EDIT.
// source: importer.proto

package protob

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PageData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JsonData             string   `protobuf:"bytes,2,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageData) Reset()         { *m = PageData{} }
func (m *PageData) String() string { return proto.CompactTextString(m) }
func (*PageData) ProtoMessage()    {}
func (*PageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_394990ff89e0d02b, []int{0}
}

func (m *PageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageData.Unmarshal(m, b)
}
func (m *PageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageData.Marshal(b, m, deterministic)
}
func (m *PageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageData.Merge(m, src)
}
func (m *PageData) XXX_Size() int {
	return xxx_messageInfo_PageData.Size(m)
}
func (m *PageData) XXX_DiscardUnknown() {
	xxx_messageInfo_PageData.DiscardUnknown(m)
}

var xxx_messageInfo_PageData proto.InternalMessageInfo

func (m *PageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PageData) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

type TitleData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JsonData             int32    `protobuf:"varint,2,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TitleData) Reset()         { *m = TitleData{} }
func (m *TitleData) String() string { return proto.CompactTextString(m) }
func (*TitleData) ProtoMessage()    {}
func (*TitleData) Descriptor() ([]byte, []int) {
	return fileDescriptor_394990ff89e0d02b, []int{1}
}

func (m *TitleData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TitleData.Unmarshal(m, b)
}
func (m *TitleData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TitleData.Marshal(b, m, deterministic)
}
func (m *TitleData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TitleData.Merge(m, src)
}
func (m *TitleData) XXX_Size() int {
	return xxx_messageInfo_TitleData.Size(m)
}
func (m *TitleData) XXX_DiscardUnknown() {
	xxx_messageInfo_TitleData.DiscardUnknown(m)
}

var xxx_messageInfo_TitleData proto.InternalMessageInfo

func (m *TitleData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TitleData) GetJsonData() int32 {
	if m != nil {
		return m.JsonData
	}
	return 0
}

type PageNameData struct {
	PageId               string   `protobuf:"bytes,1,opt,name=pageId,proto3" json:"pageId,omitempty"`
	NameStart            int32    `protobuf:"varint,2,opt,name=name_start,json=nameStart,proto3" json:"name_start,omitempty"`
	JsonData             string   `protobuf:"bytes,3,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageNameData) Reset()         { *m = PageNameData{} }
func (m *PageNameData) String() string { return proto.CompactTextString(m) }
func (*PageNameData) ProtoMessage()    {}
func (*PageNameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_394990ff89e0d02b, []int{2}
}

func (m *PageNameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageNameData.Unmarshal(m, b)
}
func (m *PageNameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageNameData.Marshal(b, m, deterministic)
}
func (m *PageNameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageNameData.Merge(m, src)
}
func (m *PageNameData) XXX_Size() int {
	return xxx_messageInfo_PageNameData.Size(m)
}
func (m *PageNameData) XXX_DiscardUnknown() {
	xxx_messageInfo_PageNameData.DiscardUnknown(m)
}

var xxx_messageInfo_PageNameData proto.InternalMessageInfo

func (m *PageNameData) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *PageNameData) GetNameStart() int32 {
	if m != nil {
		return m.NameStart
	}
	return 0
}

func (m *PageNameData) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

type Success struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_394990ff89e0d02b, []int{3}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

func (m *Success) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func init() {
	proto.RegisterType((*PageData)(nil), "PageData")
	proto.RegisterType((*TitleData)(nil), "TitleData")
	proto.RegisterType((*PageNameData)(nil), "PageNameData")
	proto.RegisterType((*Success)(nil), "Success")
}

func init() { proto.RegisterFile("importer.proto", fileDescriptor_394990ff89e0d02b) }

var fileDescriptor_394990ff89e0d02b = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2d, 0xc8,
	0x2f, 0x2a, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe3, 0xe2, 0x08, 0x48,
	0x4c, 0x4f, 0x75, 0x49, 0x2c, 0x49, 0x14, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x92, 0xe2, 0xe2, 0xc8, 0x2a, 0xce, 0xcf, 0x03, 0xc9,
	0x49, 0x30, 0x81, 0x45, 0xe1, 0x7c, 0x25, 0x73, 0x2e, 0xce, 0x90, 0xcc, 0x92, 0x1c, 0x74, 0x8d,
	0xac, 0x58, 0x35, 0xb2, 0x22, 0x69, 0x4c, 0xe4, 0xe2, 0x01, 0x59, 0xe8, 0x97, 0x98, 0x0b, 0xd1,
	0x2b, 0xc6, 0xc5, 0x56, 0x90, 0x98, 0x9e, 0xea, 0x09, 0xb3, 0x18, 0xca, 0x13, 0x92, 0xe5, 0xe2,
	0xca, 0x4b, 0xcc, 0x4d, 0x8d, 0x2f, 0x2e, 0x49, 0x2c, 0x2a, 0x81, 0x9a, 0xc2, 0x09, 0x12, 0x09,
	0x06, 0x09, 0xa0, 0x58, 0xc1, 0x8c, 0xe6, 0x36, 0x4d, 0x2e, 0xf6, 0xe0, 0xd2, 0xe4, 0xe4, 0xd4,
	0xe2, 0x62, 0x21, 0x39, 0x2e, 0xae, 0x62, 0x08, 0x33, 0xad, 0x34, 0x07, 0x6c, 0x03, 0x47, 0x10,
	0x92, 0x88, 0xd1, 0x54, 0x46, 0x2e, 0x0e, 0x4f, 0x68, 0x88, 0x08, 0x69, 0x72, 0xf1, 0x65, 0xe6,
	0xa5, 0xa7, 0x16, 0x97, 0xc0, 0x43, 0x84, 0x53, 0x0f, 0xc6, 0x94, 0xe2, 0xd0, 0x83, 0x9a, 0xa9,
	0xc4, 0xa0, 0xc1, 0x28, 0xa4, 0xcd, 0xc5, 0x0f, 0x51, 0x8a, 0x08, 0x04, 0x2e, 0x3d, 0x38, 0x1b,
	0x4d, 0xb1, 0x21, 0x97, 0x10, 0xc2, 0x5c, 0xb8, 0xc7, 0x79, 0xf5, 0x90, 0xb9, 0xa8, 0x5a, 0x9c,
	0x38, 0xa2, 0xd8, 0xc0, 0xf1, 0x93, 0x94, 0x04, 0xa1, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x21, 0x85, 0x92, 0xad, 0xb9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImporterClient is the client API for Importer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImporterClient interface {
	IngestPageData(ctx context.Context, opts ...grpc.CallOption) (Importer_IngestPageDataClient, error)
	IngestTitleData(ctx context.Context, opts ...grpc.CallOption) (Importer_IngestTitleDataClient, error)
	IngestPageNameData(ctx context.Context, opts ...grpc.CallOption) (Importer_IngestPageNameDataClient, error)
}

type importerClient struct {
	cc *grpc.ClientConn
}

func NewImporterClient(cc *grpc.ClientConn) ImporterClient {
	return &importerClient{cc}
}

func (c *importerClient) IngestPageData(ctx context.Context, opts ...grpc.CallOption) (Importer_IngestPageDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Importer_serviceDesc.Streams[0], "/Importer/ingestPageData", opts...)
	if err != nil {
		return nil, err
	}
	x := &importerIngestPageDataClient{stream}
	return x, nil
}

type Importer_IngestPageDataClient interface {
	Send(*PageData) error
	CloseAndRecv() (*Success, error)
	grpc.ClientStream
}

type importerIngestPageDataClient struct {
	grpc.ClientStream
}

func (x *importerIngestPageDataClient) Send(m *PageData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *importerIngestPageDataClient) CloseAndRecv() (*Success, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Success)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *importerClient) IngestTitleData(ctx context.Context, opts ...grpc.CallOption) (Importer_IngestTitleDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Importer_serviceDesc.Streams[1], "/Importer/ingestTitleData", opts...)
	if err != nil {
		return nil, err
	}
	x := &importerIngestTitleDataClient{stream}
	return x, nil
}

type Importer_IngestTitleDataClient interface {
	Send(*TitleData) error
	CloseAndRecv() (*Success, error)
	grpc.ClientStream
}

type importerIngestTitleDataClient struct {
	grpc.ClientStream
}

func (x *importerIngestTitleDataClient) Send(m *TitleData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *importerIngestTitleDataClient) CloseAndRecv() (*Success, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Success)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *importerClient) IngestPageNameData(ctx context.Context, opts ...grpc.CallOption) (Importer_IngestPageNameDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Importer_serviceDesc.Streams[2], "/Importer/ingestPageNameData", opts...)
	if err != nil {
		return nil, err
	}
	x := &importerIngestPageNameDataClient{stream}
	return x, nil
}

type Importer_IngestPageNameDataClient interface {
	Send(*PageNameData) error
	CloseAndRecv() (*Success, error)
	grpc.ClientStream
}

type importerIngestPageNameDataClient struct {
	grpc.ClientStream
}

func (x *importerIngestPageNameDataClient) Send(m *PageNameData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *importerIngestPageNameDataClient) CloseAndRecv() (*Success, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Success)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImporterServer is the server API for Importer service.
type ImporterServer interface {
	IngestPageData(Importer_IngestPageDataServer) error
	IngestTitleData(Importer_IngestTitleDataServer) error
	IngestPageNameData(Importer_IngestPageNameDataServer) error
}

func RegisterImporterServer(s *grpc.Server, srv ImporterServer) {
	s.RegisterService(&_Importer_serviceDesc, srv)
}

func _Importer_IngestPageData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImporterServer).IngestPageData(&importerIngestPageDataServer{stream})
}

type Importer_IngestPageDataServer interface {
	SendAndClose(*Success) error
	Recv() (*PageData, error)
	grpc.ServerStream
}

type importerIngestPageDataServer struct {
	grpc.ServerStream
}

func (x *importerIngestPageDataServer) SendAndClose(m *Success) error {
	return x.ServerStream.SendMsg(m)
}

func (x *importerIngestPageDataServer) Recv() (*PageData, error) {
	m := new(PageData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Importer_IngestTitleData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImporterServer).IngestTitleData(&importerIngestTitleDataServer{stream})
}

type Importer_IngestTitleDataServer interface {
	SendAndClose(*Success) error
	Recv() (*TitleData, error)
	grpc.ServerStream
}

type importerIngestTitleDataServer struct {
	grpc.ServerStream
}

func (x *importerIngestTitleDataServer) SendAndClose(m *Success) error {
	return x.ServerStream.SendMsg(m)
}

func (x *importerIngestTitleDataServer) Recv() (*TitleData, error) {
	m := new(TitleData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Importer_IngestPageNameData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImporterServer).IngestPageNameData(&importerIngestPageNameDataServer{stream})
}

type Importer_IngestPageNameDataServer interface {
	SendAndClose(*Success) error
	Recv() (*PageNameData, error)
	grpc.ServerStream
}

type importerIngestPageNameDataServer struct {
	grpc.ServerStream
}

func (x *importerIngestPageNameDataServer) SendAndClose(m *Success) error {
	return x.ServerStream.SendMsg(m)
}

func (x *importerIngestPageNameDataServer) Recv() (*PageNameData, error) {
	m := new(PageNameData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Importer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Importer",
	HandlerType: (*ImporterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ingestPageData",
			Handler:       _Importer_IngestPageData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ingestTitleData",
			Handler:       _Importer_IngestTitleData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ingestPageNameData",
			Handler:       _Importer_IngestPageNameData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "importer.proto",
}
